// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAn6u1h960lHct2RgnWERxV_33Mz3MiE',
    appId: '1:505356596324:android:610097e6dd50db53f69b71',
    messagingSenderId: '505356596324',
    projectId: 'chinese-study-application',
    storageBucket: 'chinese-study-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy7vMILCHST-5uaJ6jRaCfh5MY2mqiz1g',
    appId: '1:505356596324:ios:e42c261a70497619f69b71',
    messagingSenderId: '505356596324',
    projectId: 'chinese-study-application',
    storageBucket: 'chinese-study-application.appspot.com',
    iosClientId: '505356596324-t51s519vn1oaj42e6l5t29br1vc3spgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chineseStudyApplicaion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy7vMILCHST-5uaJ6jRaCfh5MY2mqiz1g',
    appId: '1:505356596324:ios:e42c261a70497619f69b71',
    messagingSenderId: '505356596324',
    projectId: 'chinese-study-application',
    storageBucket: 'chinese-study-application.appspot.com',
    iosClientId: '505356596324-t51s519vn1oaj42e6l5t29br1vc3spgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chineseStudyApplicaion',
  );
}
